### PR TITLE
pagination on server side, fixes #1281

### LINKED ISSUE #1281: Demographics vs. Lab Results is very slow.
Demographics vs. Lab Results is very slow simply because each patient has about 10 lab tests. Just checking to see if there is any option to speed this up. - Bob Hoyt.

This is using the nhanes data and the new report:  Reports->Client->Clinic Statistics: Demographics vs. Lab Results

### PR DESCRIPTION
**Pull request by naveen17797**
Fixes #1281 
@tmccormi try this PR, i hope it almost solved the issue.

### CODE REVIEW

**Comment by tmccormi** [comment]
@growlingflea will take a look at this on Sunday ...

**Comment by aethelwulffe** [comment]
@tmccormi is it sunday yet, or shall we look at what this is supposed to do (limit query time I think).

**Comment by naveen17797** [comment]
@aethelwulffe yeah its about reducing the query time.

**Comment by aethelwulffe** [comment]
Not sure if I understand this yet.  I will review later.

**Pull request merged**
