### PR TITLE
Autocomplete function has been added to patients>add new

### PR DESCRIPTION
**Pull request by naveen17797**
screenshot from 2018-03-05 20-39-49
- in hospitals this type of autocomplete function is necessary, so that there is no need to type the same name again and again
- it will help to add patients quickly and reduce the time spent in typing

### CODE REVIEW

**Comment by naveen17797** [comment]
currently in this PR it is enabled only to the fname, mname, lname.
If this approach is accepted then we could extend it to fields wherever it is needed.

**Comment by naveen17797** [comment]
@aethelwulffe  @teryhill @pri2si17-1997  please review this

**Comment by aethelwulffe** [comment]
Heh, this is cool Naveen, but also scary in a way.  With all the messed up spellings out there...uh...
How about we put in a toggle to enable this for user settings (accessible right on the demographics screen).  Personally, I think most folks would rather finish typing at their normal 120 words per minute than stop and pick an option.

**Comment by aethelwulffe** [comment]
I notice TWO copies of Naveen showed up....

**Comment by naveen17797** [comment]
I have added my name 2 times in DB, that's why it showed up, need to fix it

**Comment by aethelwulffe** [comment]
What happens if you have 50 patients named "Michael" or "Muhammed"?  Does it list all of them?  I suggest we test this against a very very large database.

**Comment by naveen17797** [comment]
Yes, i need to fix that, if a similar name is present then we can show it only one time .

**Comment by naveen17797** [comment]
screenshot from 2018-03-06 17-17-29
fixed

**Comment by naveen17797** [comment]
@aethelwulffe @teryhill  i would like to know where this feature is most useful in this application, i have just explored only primary areas of it , i hope you know where it will help to reduce time

**Comment by aethelwulffe** [comment]
Hi @naveen17797 ,
Could you put in a "use search enhancements" feature toggle into this?

**Comment by naveen17797** [comment]
@aethelwulffe like making a user to choose whether they need search enhancements or not?

**Comment by aethelwulffe** [comment]
I would put it in globals and in user preferences, not in the user admin/creation.  I think we need to move more things out of the user creation modal window, and into user preferences.  Additionally, there is the whole "address book" part of the user table.  External users are stored in the users table as contacts.  Many of the user table fields are only accessible through the address book.  Many of these fields are very useful, and most should be added to the user preferences settings.  Admin view of these should still be available somewhere, though.  For now, it is the ancient clunky address book.

**Comment by aethelwulffe** [comment]
Caveat:
Currently the only way to enable granular access control over what users see what patients is the TAGS system.  The ACL by Facility enhancement has failed to get done several times now.  Nonetheless, there must be a way to filter the search results to only names that the user actually has access to, probably even in the type-ahead feature.  @teryhill @tmccormi  how do you guys feel about this level of paranoia?

**Comment by teryhill** [comment]
@aethelwulffe where are you in your thought process on this. 

Where are you on the facility ACL modification.

Where is Waldo?

**Comment by aethelwulffe** [comment]
Waldo is saying "Don't implement search features unless ACL and TAG rules are minded.

**Comment by naveen17797** [comment]
So patients with restriction tags should not be shown in autocomplete feature?

**Comment by aethelwulffe** [comment]
Where are we on this folks?

**Comment by tmccormi** [comment]
Let's re-do this PR as just an commit of useful autocompete functions that can be used.  Implementing this feature in the UI shown (New/Search) is not really useful, but the functions are.

**Comment by aethelwulffe** [comment]
@Trodrige Can you grab the little /ajax part of this (which is the real code) and use it in the report engine?

**Comment by teryhill** [comment]
Any more progress on this?

**Comment by aethelwulffe** [comment]
@naveen17797 The autocomplete part of this is indeed valuable as a core function.  I think I agree with Tony that as a feature, it doesn't gain you much considering the access control hooks that are required in this context, but we really want the library!

**Comment by naveen17797** [comment]
yes @teryhill  @aethelwulffe 
lets redo the PR with access controls like a function which can be used in any form fields, so as to take data from particular column of table and fill the field
more or less like 
function autcomplete($tablename, $columnname, $restrictionclause) { }
like this

**Comment by aethelwulffe** [comment]
When we take this on...

function autcomplete($tablename, $columnname, $restrictionclause, $option1, $etc...) { }

Needs to work with `lists`, layout_options etc...

**Comment by aethelwulffe** [comment]
Stale.  If this is an active PR, please create new.

**Pull request closed without merging**
