### PR TITLE
The User activity report 

### PR DESCRIPTION
**Pull request by growlingflea**
Reports user activity by pulling data from the log table.  The user can see the total sum of time

each active user was logged in, show the approximate time of each session (log in to log out, or log in to the last activity before the following login),
and sum of sessions given a time period.  Full seaching capability of each column available, using datatables10 capabilities."

### CODE REVIEW

**Comment by growlingflea** [comment]
@tmccormi The bug-free much improved user report :)

**Comment by growlingflea** [comment]
@tmccormi  I added the new Datatables files to assets and made some quick improvements to the interface.  The new bootstrap buttons should be working too.

**Comment by tmccormi** [comment]
@growlingflea 
Functional testing:  
1) This works well with my limited test data, need to test it in a real data set.  Note: this could replace the current log report completely, since you added a show activity view

2) The menu location is wrong, please  move it to Admin->Other-> (near Log)

3) Using the Themes Light and Prizm the button TEXT is invisible, it's fin using 'Tan'  
userreport-buttons

4) Making it full size has issues.
userreport-fullsize

5) Export as XLSZ is cool, but can we add a CSV button please?

**Comment by tmccormi** [comment]
Seriously: all it lacks to completely replace the Log viewer is a Patient column/search.

**Comment by tmccormi** [comment]
Testing updated PR

**Comment by tmccormi** [comment]
@aethelwulffe @teryhill This is ready for merging, in my opinion.

**Comment by tmccormi** [comment]
replaced by #1257

**Pull request closed without merging**
