### PR TITLE
Fixed history tracking form #1462

### PR DESCRIPTION
**Pull request by muarachmann**
This fixes the referenced issue #1462 @Ngai-E can you test this. @aethelwulffe i think i made the fix here is what i get. 
Screen Shot 2019-05-16 at 1 23 38 AM

### CODE REVIEW

**Comment by robbyoconnor** [comment]
does  `$GLOBALS['web_root'] ` account for things like it may be in `/opt/ehr`?

**Comment by muarachmann** [comment]
> does `$GLOBALS['web_root'] ` account for things like it may be in `/opt/ehr`?

Nope but you can manually set it. Take a look here - https://github.com/LibreHealthIO/lh-ehr/blob/master/interface/globals.php

**Comment by aethelwulffe** [comment]
Personally, I would recommend looking at that in several ways.
1.  Use PHP standard variable $_SERVER.
<?php 
   $path = $_SERVER['DOCUMENT_ROOT'];
   $path .= "/common/header.php";
   include_once($path);
?>
2.  Make your own GLOBAL in /interface/globals.php
3.  Call /library/headers.inc.php then write a function in there that allows you to include a specific file set.
4.  A combination of the above.
NOTE:  This must be either a custom alteration to any of the above, or within a specific module (or under /docker), or be done with a dynamic structure or a validation check.  For instance, none of my servers have an /opt/ directory in the path.  I have either var/www or /htdocs.  If it is custom, but is to be included in the master repo, set another global configuration variable in /library/globals.inc.php where you can then enter a directory structure such as $GLOBALS['../../opt/'].

**Comment by robbyoconnor** [comment]
> Nope but you can manually set it. Take a look here - https://github.com/LibreHealthIO/lh-ehr/blob/master/interface/globals.php

That is problematic. Don't assume things are set up in any way. Webroots will differ from system to system.

**Comment by muarachmann** [comment]
You asked a question and i replied. This has nothing to do with the pull
request

**Comment by muarachmann** [comment]
The modules dir is only a relative path here and would be picked up where ever it is placed

**Comment by robbyoconnor** [comment]
> You asked a question and i replied. This has nothing to do with the pull request since `

No, the question has everything to do since you are using that variable(`$GLOBALS['web_root']`) is used here. Are you sure this would work if I chose to place this in `/opt/foobar` ?

**Comment by robbyoconnor** [comment]
> You asked a question and i replied. This has nothing to do with the pull request since `

No, the question has everything to do since that variable(`$GLOBALS['web_root']`) is used here. Are you sure this would work if I chose to place this in `/opt/foobar` ? Would you code still pick up the proper path?

**Comment by muarachmann** [comment]
> > You asked a question and i replied. This has nothing to do with the pull request since `
> 
> No, the question has everything to do since that variable(`$GLOBALS['web_root']`) is used here. Are you sure this would work if I chose to place this in `/opt/foobar` ? Would you code still pick up the proper path?

@robbyoconnor not sure if i get you well but in globals.php i have this 
```$webserver_root = dirname(dirname(__FILE__));```  and  this ```$server_document_root = realpath($_SERVER['DOCUMENT_ROOT']);```  which boils down to ``$web_root = substr($webserver_root, strspn($webserver_root ^ $server_document_root, "\0"));```

Before having this ```$GLOBALS['webroot'] = $web_root;```. So i don't get the stuff maybe an example will clear me off

**Comment by aethelwulffe** [comment]
@robbyoconnor I think you have no idea what is going on here.  Please limit yourself to constructive conduct, and only within a realm in which you are fully competent when reviewing work.

**Comment by robbyoconnor** [comment]
> @robbyoconnor I think you have no idea what is going on here. Please limit yourself to constructive conduct, and only within a realm in which you are fully competent when reviewing work.

My apologies...I was concerned if it handled webroots in a flexible way -- that's all -- sorry for ruffling feathers here.

**Comment by aethelwulffe** [comment]
The variable names you are seeing are not what you may think they are.  "$GLOBALS" isn't even a session variable array.  It is an array that is called with each and every script.  It is only global in the sense that the values are common and shared across the application.  It has nothing to do with server variables.
-I am regretting coming back.  I think I need to re-evaluate again.

**Comment by robbyoconnor** [comment]
> The variable names you are seeing are not what you may think they are. "$GLOBALS" isn't even a session variable array. It is an array that is called with each and every script. It is only global in the sense that the values are common and shared across the application. It has nothing to do with server variables.
> -I am regretting coming back. I think I need to re-evaluate again.

My apologies then for misunderstanding, I withdraw any and all opinions :smiley_cat:

**Comment by robbyoconnor** [comment]
> The variable names you are seeing are not what you may think they are. "$GLOBALS" isn't even a session variable array. It is an array that is called with each and every script. It is only global in the sense that the values are common and shared across the application. It has nothing to do with server variables.

My apologies then for misunderstanding, I withdraw any and all opinions :smiley_cat: 

> -I am regretting coming back. I think I need to re-evaluate again.

What do you mean here?

**Comment by aethelwulffe** [comment]
With every interaction, after you have made folks upset, there are folks that feel unwelcome.  We have lost three vendors that used to contribute high quality stuff here.  They have taken the code, and are doing wonderful in-house stuff that they are sharing privately, but with the stipulation that it not be pushed to this repo.
You have crapped all over this project Robbie.  I thought if I came back I could bring some of the people that used to contribute (I still work with about a dozen), because it seemed like you had calmed down and were minding your own business.  After your posts today, I got told I needed to remove my pull requests that have someone's shared code in them.  That stuff was vital to this project going forward.  You have made this project unviable.
It is all yours now.  Knock yourself out.

**Comment by robbyoconnor** [comment]
@aethelwulffe I didn't crap all over this -- I just voiced a concern which was a misunderstanding... There wasn't anything bad... I don't think @muarachmann was put off. This is a misunderstanding in this instance, I'm sorry.

**Comment by robbyoconnor** [comment]
I cleaned this up -- my apologies again

**Comment by KoniKodes** [comment]
What is the status of this PR? Is it ready to be merged?

**Comment by muarachmann** [comment]
Merging this too along. Looks fine till now

**Pull request merged**
