### PR TITLE
Fix #983: Mousetip in Patient Search

### LINKED ISSUE #983: Mousetip in Patient Search
Hover over the last name field in a Patient Finder row.  This field has an assigned background color, and shows a refresh icon that was intended to be a temp placeholder for something else as a replacement mouse tooltip.

-A very ugly and cheezy homemade-looking image...and not used in the right context.

### PR DESCRIPTION
**Pull request by apooravc**
Fixes #983 
Following the description given in the issue, the background colors represent the column by which table is sorted currently and by default when you open it for the first time, it is sorted by Last name. Sort by any column and it will show those background colors in entries of sorted column. I think those are fine.

Preview of changes done:
img1

- Deleted that refresh icon.

- When user hovers over a row, it becomes transparent as illustrated by third row in preview. This used to happen with only even row, now it does with both even/odd row.

One way to see the changes _locally_ would be as follows:
1) Clone my repo via `git clone https://github.com/apooravc/LibreEHR.git`
2) After cloning, only the master branch would be available locally. Enter `git checkout -b update-finder-UI origin/update-finder-UI` or `git branch update-finder-UI origin/update-finder-UI` to get the branch _update-finder-UI_ locally.
3) The changes could then be seen on main page.

@aethelwulffe Please have a look.

### CODE REVIEW

**Comment by aethelwulffe** [comment]
That looks really good.
Adding this to my test line-up.

**Comment by pri2si17-1997** [comment]
@apooravc Not working as intended. I can't find any difference, I tested it on my local machine. @aethelwulffe @teryhill can you please test it.

**Comment by aethelwulffe** [comment]
@pri2si17-1997 I need a little more time...doing reviews amidst the morning chaos.

**Comment by pri2si17-1997** [comment]
Ok @aethelwulffe . Take your time. :slightly_smiling_face:

**Comment by aethelwulffe** [comment]
That is because only style_light was changed.

**Comment by pri2si17-1997** [comment]
I have the same theme, then also I can't see any change. :worried:

**Comment by teryhill** [comment]
We need just 2 themes with a color picker and font picker.

**Comment by aethelwulffe** [comment]
Yes, we just need two themes.  Agreed.

**Comment by apooravc** [comment]
@pri2si17-1997 I can see my changes on my branch on Github but those changes aren't pulled down when checking out the branch to my local repo. Strange behavior.

**Comment by aethelwulffe** [comment]
I am only seeing one commit.

**Comment by aethelwulffe** [comment]
https://github.com/apooravc/LibreEHR/tree/update-finder-UI shows only one commit.  Git-push?

**Comment by apooravc** [comment]
@aethelwulffe Yes, that branch is one commit ( see commit sub tab above ) ahead of master branch of official repo. You may `git checkout` or `git branch` that branch, as mentioned in my last comment, to see changes I did locally.

**Comment by aethelwulffe** [comment]
This PR is still not reflecting additional commits.

**Comment by apooravc** [comment]
@aethelwulffe Yes, I've no clue why it's behaving this way. The three changes I did in that single commit are not reflecting upon viewing EHR (based on branch _update-finder-UI_) locally.

**Comment by aethelwulffe** [comment]
Well, either we are going to have to get you to push a new branch, or we are going to have to give you broader permissions on this repo to write branches to here so that we don't have that issue.

**Comment by apooravc** [comment]
I'll check pushing a new branch.

**Comment by teryhill** [comment]
@apooravc I cannot get this to work "When user hovers over a row, it becomes transparent as illustrated by third row in preview. This used to happen with only even row, now it does with both even/odd row."

All I get is the field changing to a reddish color no matter what field. Tried it with light and tan styles

**Comment by apooravc** [comment]
Continued on Gitlab as [MR 1104](https://gitlab.com/librehealth/ehr/lh-ehr/merge_requests/1104). Closing this.

**Pull request closed without merging**
