### PR TITLE
fix for folders with dot causing bug in updater

### PR DESCRIPTION
**Pull request by naveen17797**
fixes a bug which causes folders to appear as files in updater download module

### CODE REVIEW

**Comment by naveen17797** [comment]
still not working, need to figure the error caused when applying #1180 , dont merge or test it for now

**Comment by aethelwulffe** [comment]
This is actually interesting, but Otay! :)

**Comment by naveen17797** [comment]
ready for testing, @teryhill @aethelwulffe 
finally found what caused that.

**Comment by aethelwulffe** [comment]
I will run this test and post my findings from Monday's round of tests this afternoon.

**Comment by aethelwulffe** [comment]
I didn't get back to this.  Sorry.
Test was sat for updater.
What specific directory names have dots?  We should not really allow those anyway.  Our asset dir should use the naming convention for js stuff (commonly has dots) as hyphens.

**Comment by naveen17797** [comment]
actually there is a directory with dot in PR #1180 
 assets/js/Buttons-1.5.1
this make the updater think that it was a file, since pathinfo($filename, PATHINFO_EXTENSION) returned a extension of that folder(which i didnt expect, i thought it would only return extesnion when it is a file), so i altered the logic,
you can test by going to developer mode
choose #1180  and applying it @aethelwulffe

**Comment by aethelwulffe** [comment]
Our naming convention (remarked when that PR was put out) is to replace 
dots with hyphens or underscores.  headers.inc.php kinda demands that 
for at least one of the functions.

**Comment by naveen17797** [comment]
finally tutorial for the updater
https://www.youtube.com/watch?v=f42BiTp75Z8

**Comment by aethelwulffe** [comment]
PERFECT!

**Pull request merged**
