### PR TITLE
 White Space Present In Top Right On Navbar Gone.

### PR DESCRIPTION
**Pull request by ahanipeitra1994**
I fixed the issue #1536 now the white space available at the top right corner of the ''navbar" is not showing again.

image

### CODE REVIEW

**Comment by muarachmann** [comment]
Okay one thing that really pissed me off! checking this immediately

**Comment by muarachmann** [comment]
@ahanipeitra1994 please name your branches something shorter if you are out of names just use `fix-issue_number` :)

**Comment by muarachmann** [comment]
@ahanipeitra1994 just checked white space gone but I have 2 ones at the top, see below, I chosed those colours so you would see clearly. Have fun debugging

Screen Shot 2020-07-04 at 1 50 56 AM

Screen Shot 2020-07-04 at 1 52 19 AM

**Comment by ahanipeitra1994** [comment]
I tested but did not notice please i will do the adjustment now

**Pull request closed without merging**
