### PR TITLE
interface\new library refactor

### PR DESCRIPTION
**Pull request by MigDinny**
#915 

now using call_required_libraries and jquery upgraded to latest version

### CODE REVIEW

**Comment by aethelwulffe** [comment]
Please indicate a merge order for these related PR's.  We don't want to create conflicts.
Which one first?

**Comment by MigDinny** [comment]
@aethelwulffe the order is the id order (#926 -> this, the creation order)

don't know if i made it clear :D

**Comment by MigDinny** [comment]
@aethelwulffe yes, it's better to respect the order first. If any merge conflict happens i will fix it easily

in the end of these merges I will check headers.inc.php file because i touched it so many times i'm afraid he gets broken or something

**Comment by MigDinny** [comment]
Conflicts with master branch solved in the last merge commit.

**Pull request closed without merging**
