### PR TITLE
Fixed Broken Page #1299

### PR DESCRIPTION
**Pull request by punwai**
The require files seems to be broken.

### CODE REVIEW

**Comment by muarachmann** [comment]
@punwai please what page does this PR attempts to fix?

**Comment by punwai** [comment]
#1299

**Comment by muarachmann** [comment]
> #1299

Okay please always do reference it. Testing this

**Comment by muarachmann** [comment]
@punwai please avoid master naming your branch.

**Comment by punwai** [comment]
@muarachmann Sorry, I will keep that in mind next time. I forgot to branch out before editing

**Comment by punwai** [comment]
Did the code work? @muarachmann

**Comment by muarachmann** [comment]
can you please checkout to another branch. and recommit

**Pull request closed without merging**
