### PR TITLE
Dropdown fix mergeable

### PR DESCRIPTION
**Pull request by RAJAGOPALAN-GANGADHARAN**

### CODE REVIEW

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
This is the trail pr for a pr which created merge conflicts. Hope this is clear of conflicts 😄

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Well it is working well can anyone review it?

**Comment by aethelwulffe** [comment]
@RAJAGOPALAN-GANGADHARAN My schedule is that I have been able to do little here until April 1.  That is tomorrow (though my deadline got extended to the 2nd) and I will be working to catch up everything asap. 
  I will pull and test this for review by Tuesday.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
OK 😄 @aethelwulffe

**Comment by aethelwulffe** [comment]
@muarachmann Simple changes here, please check.

**Pull request merged**
