### PR TITLE
translate text corrections to english

### PR DESCRIPTION
**Pull request by aethelwulffe**
Round 1.  Fixing the ENGLISH before adding the Spanish translations.  To be checked against whatever list someone else has come up with.
-Note, one item involves removing an ICD-9 code from Bronchitis form.  The other translatable items in there need to have entries made for ICD-10, probably push to the fee sheet, or simply delete the old funky form.

### CODE REVIEW

**Comment by aethelwulffe** [comment]
@teryhill You think I found all of them?

**Comment by teryhill** [comment]
If you did not we will see them eventually cause they will not translate.

**Comment by aethelwulffe** [comment]
Someone else check this so we can merge it and get the translation folks on track.

**Comment by VirginiaBalseiro** [comment]
Any idea when this will be merged?
I need those Greek tags in the Spanish version gone ASAP for the docs I'm working on.
Thanks.

**Comment by robbyoconnor** [comment]
Perfect -- I will update the demo right now!

**Comment by aethelwulffe** [comment]
This is only the English text changes.  Working on PR for Spanish.

**Comment by robbyoconnor** [comment]
Still pulled in -- let me know when it's done

**Pull request merged**
