### PR TITLE
fix Review of Systems form submit

### PR DESCRIPTION
**Pull request by muarachmann**

### CODE REVIEW

**Comment by muarachmann** [comment]
Fix for #1228. @teryhill , @tmccormi i left some comments on this issue. I need a go ahead for the validations necessary or should i come up with one??. with that @2208Abhinav can continue with his report generation too.
screenshot from 2018-08-17 19-43-30

and here the review. But i dont like the idea of it saving the form even when no box is being checked. I think that should be a validation

screenshot from 2018-08-17 20-19-18

**Comment by aethelwulffe** [comment]
1.  Needs spacing between output of things like "FEVER:yes"
2.  Mind checking out https://github.com/LibreHealthIO/lh-ehr-contribs/tree/Button_ros and building it up as a replacement form so we can drop this *and* the other ROS form?

**Comment by aethelwulffe** [comment]
Yes, I believe so.  I have not used this form in years and years....wait....I have never really used this form...  :)

**Comment by tmccormi** [comment]
@muarachmann sorry, way behind.  I'm going to test this tonight and approve it if I agree with @aethelwulffe (which I'm pretty sure I will)

**Pull request merged**
