### PR TITLE
Procedures process UI update

### PR DESCRIPTION
**Pull request by Perseus**
Small UI revamp for the procedures/orders configuration screen. 

Changes: 
- Changed table and button style of base page
- Change modal/dialog box usage to iziModal
- Added some validation rules for the creation and editing of procedures

To-do: 
- Explanations of form elements so as to make it easier for the user to understand what information they need to put in
- Override default page CSS with bootstrap CSS to change button designs in the modals

Screenshots:

### CODE REVIEW

**Comment by aethelwulffe** [comment]
NIce!
(art scribbling note to add to review list)

**Comment by aethelwulffe** [comment]
Procedures/Orders update...not so much "Provider" (means "Doctor" etc...).

**Comment by Perseus** [comment]
@aethelwulffe Changed title and description 😄

**Comment by aethelwulffe** [comment]
Good title!

**Pull request merged**
