### PR TITLE
Validation for blank current password

### PR DESCRIPTION
**Pull request by Priyanka488**
Fix : #1451 
Changes made in : library/authentication/password_change.php
Added validation to check blank current password field on clicking save button.

cc

### CODE REVIEW

**Comment by KoniKodes** [comment]
@aethelwulffe @muarachmann 
Hi, is it possible to have this reviewed or merged?
This is the last week of the Outreachy application round and I'm trying to get all the ducks in a row...

**Comment by muarachmann** [comment]
@Priyanka488 simple fix.Did you take a look at the link i sent. It could be more elegant that way. Nice though

**Comment by Priyanka488** [comment]
@muarachmann I saw your PR, but I am still learning ajax and jquery. It was difficult for me to understand.
So, I thought if doing it like this.

**Comment by muarachmann** [comment]
Oh all is fine :)

**Pull request merged**
