### PR TITLE
Misc_Billing_Form Changes.

### PR DESCRIPTION
**Pull request by teryhill**
These changes allow the EPSDT options, The box 17 options, The
electronic resubmission of claims. #269

### CODE REVIEW

**Comment by aethelwulffe** [comment]
pushing to ARSP prod in an hour or so.

**Comment by aethelwulffe** [comment]
In the form, where does provider qualifier code come from (17a)?  Getting a blank dropdown.  Probably because I am testing it in an older code set.  I did notice that the older code has exclude from insurance (dang useful thing) and it doesn't seem to be here....

**Comment by teryhill** [comment]
I will send the exclude stuff up in a commit after this on is in place( Tony wants things seperate) so don't worry it will be there.

I will send the code up to create the list for those provider qualifiers

**Comment by aethelwulffe** [comment]
That's the only missing chunk I have seen so far...but billing ppl arrive on monday...

**Comment by teryhill** [comment]
I just pushed the code for that

**Comment by tmccormi** [comment]
If Art approves it I can merge it while I'm waiting for my next flight...

**Comment by aethelwulffe** [comment]
OK.  Exhausted, but the stuff looks like it runs.  It will might be Wednesday before it sees real-life testing *here* anyway, but I am sure it can be visually evaluated before then.  Some features we are simply not users of, and I won't be able to do real-world with it.
  The CMS-1500 print branch is the missing piece here in any case, so I am going to try to test these in conjunction with each other in a prod, but the stuff seems to _run_, but that is as far as I can take it at this point.
  My vote is to merge up, hit the squashed print branch, then see what we get ASAP, so I approve this merge request.

**Comment by teryhill** [comment]
I have it running on 10 or so sites that use it and have been for five or six months.

**Comment by aethelwulffe** [comment]
Yeah, but Terry, you-all up there could be suffering from high-latitude sickness and be hallyooosenatin'.

**Pull request merged**
