### PR TITLE
MigDinny patient_report accordion

### PR DESCRIPTION
**Pull request by aethelwulffe**
Uses accordion to make the patient reports cleaner.

### CODE REVIEW

**Comment by tmccormi** [comment]
I'll test this and see.

**Comment by aethelwulffe** [comment]
Any test results?
This might be getting left behind with the PDF changes (probably not), but this is a very useful piece for folks that have to view/export data...which is everyone.

**Comment by apooravc** [comment]
Old interface:

ol1

ol2

New interface:

new1

new2

**Comment by muarachmann** [comment]
roger that @apooravc

**Comment by aethelwulffe** [comment]
Thank you.  I have thought so for a while.
- @MigDinny

**Pull request merged**
