### PR TITLE
Prevent unauthenticated admin access to sql_upgrade.php

### PR DESCRIPTION
**Pull request by maggienegm**

### CODE REVIEW

**Comment by aethelwulffe** [comment]
And how does someone access sql_upgrade.php at this point?  There is no menu option as yet, correct?  This is one of the files that are typically configured (including the setup procedure) to be inaccessible by configuration except as localhost on the server, or another single access point.  It it typically run by logging into an instance related to a /sites directory, then manually entering the URL.  It must be capable of determining what /sites directory it is using, but going directly to `https://myurl.org/TheRealLibreEHR/sql_upgrade.php` will not provide the global var needed without having logged in already.
-Normal install procedure recommends restricting or removing the setup/configuration files...or it is supposed to in the docs.
NOTE:  All these things need to be tested by creating more than one site, then applying changes to each.  The sites directory should look like /sites/default, /sites/myfirstsite, /sites/mysecondsite as a minimum testing scenario for any setup, configuration, backup, export-import or related code and menu changes that depend on the related GLOBALvar.

**Comment by aethelwulffe** [comment]
Just to be clear...I TOTALLY AGREE THAT THIS STUFF NEEDS LOCKING DOWN.
Depending on configuration to solve an issue like this is...not good.  Having sql_upgrade.php in the document root at all is not good.  The file should not be allowed anonymous access.
-It also seems that merely passing the ?site=mysite argument to access the login page first will suffice to allow the upgrade to run.  Simply accessing myhosturl.org/LibreEHR brings you to the setup configuration with no further ado.  You need database user data to do anything with that, but sql_upgrade.php and other things may be directly accessible when folks have not properly configured their stuff.
an "admin.php" file for sites managment:
```
<?php
require_once "version.php";

$webserver_root = dirname(__FILE__);
if (stripos(PHP_OS,'WIN') === 0)
  $webserver_root = str_replace("\\","/",$webserver_root); 
$OE_SITES_BASE = "$webserver_root/sites";
//the following should use api.inc to resolve the following stuff via adodb.  None of the sql stuff in this code is likely to work.
function sqlQuery($statement) {
  $row = @mysqli_fetch_array(mysqli_query($statement), MYSQL_ASSOC);
  return $row;
}
//
?>
<html>
<head>
<title>Libre Medical Suite Site Administration</title>
<! -- add some styling data here
<link rel='STYLESHEET' href='interface/themes/somestyle.css'>
<style>
-->
tr.head   { font-size:10pt; background-color:#cccccc; text-align:center; font-weight:bold; }
tr.detail { font-size:10pt; }
a, a:visited, a:hover { color:#0000cc; text-decoration:none; }
</style>
</head>
<body>
<center>
<p><span class='title'>LibreEHR Site Administration</span></p>
<table width='100%' cellpadding='1' cellspacing='2'>
 <tr class='head'>
  <td>Site ID</td>
  <td>DB Name</td>
  <td>Site Name</td>
  <td>Version</td>
  <td>Action</td>
 </tr>
<?php
$dh = opendir($OE_SITES_BASE);
if (!$dh) die("Cannot read directory '$OE_SITES_BASE'.");
$siteslist = array();

while (false !== ($sfname = readdir($dh))) {
  if (substr($sfname, 0, 1) == '.') continue;
  if ($sfname == 'CVS'            ) continue;
  $sitedir = "$OE_SITES_BASE/$sfname";
  if (!is_dir($sitedir)               ) continue;
  if (!is_file("$sitedir/sqlconf.php")) continue;
  $siteslist[$sfname] = $sfname;
}

closedir($dh);
ksort($siteslist);

foreach ($siteslist as $sfname) {
  $sitedir = "$OE_SITES_BASE/$sfname";
  $errmsg = '';
  ++$encount;
  $bgcolor = "#" . (($encount & 1) ? "ddddff" : "ffdddd");

  echo " <tr class='detail' bgcolor='$bgcolor'>\n";

  // Access the site's database.
  include "$sitedir/sqlconf.php";

  if ($config) {
//use each sites/directory connection here, but this part needs modification
    $dbh = mysql_connect("$host:$port", "$login", "$pass");
    if ($dbh === FALSE)
      $errmsg = "MySQL connect failed";
    else if (!mysql_select_db($dbase, $dbh))
      $errmsg = "Access to database failed";
  }

  echo "  <td>$sfname</td>\n";
  echo "  <td>$dbase</td>\n";

  if (!$config) {
    echo "  <td colspan='3'><a href='setup.php?site=$sfname'>Needs setup, click here to run it</a></td>\n";
  }
  else if ($errmsg) {
    echo "  <td colspan='3' style='color:red'>$errmsg</td>\n";
  }
  else {
    // Get site name for display.  The gl_value in the below needs verification (I didn't do that, I just guessed for this purpose)
    $row = sqlQuery("SELECT gl_value FROM globals WHERE gl_name = 'libreehr_name' LIMIT 1");
    $libreehr_name = $row ? $row['gl_value'] : '';

    // Get version indicators from the database.  NOTE:  these version indicators have not been maintained!  This is related to the whole database installation system moving to a file-per-table version scheme that has not been implemented in the LibreHealth.io code repo, which was incomplete when contributors fled the project.
    $row = sqlQuery("SHOW TABLES LIKE 'version'");
    if (empty($row)) {
      $libreehr_version = 'Unknown';
      $database_version = 0;
    }
    else {
      $row = sqlQuery("SELECT * FROM version LIMIT 1");
      $database_patch_txt = "";
      if ( !(empty($row['v_realpatch'])) && $row['v_realpatch'] != 0 ) {
        $database_patch_txt = " (" . $row['v_realpatch'] .")";
      }
      $libreehr_version = $row['v_major'] . "." . $row['v_minor'] . "." .
        $row['v_patch'] . $row['v_tag'] . $database_patch_txt;
      $database_version = 0 + $row['v_database'];
      $database_acl = 0 + $row['v_acl'];
      $database_patch = 0 + $row['v_realpatch'];
    }

    // Display relevant columns.
    echo "  <td>$libreehr_name</td>\n";
    echo "  <td>$libreehr_version</td>\n";
    if ($v_database != $database_version) {
      echo "  <td><a href='sql_upgrade.php?site=$sfname'>Upgrade Database</a></td>\n";
    }
    else if ( ($v_acl > $database_acl) ) {
      echo "  <td><a href='acl_upgrade.php?site=$sfname'>Upgrade Access Controls</a></td>\n";
    }
    else if ( ($v_realpatch != $database_patch) ) {
      echo "  <td><a href='sql_patch.php?site=$sfname'>Patch Database</a></td>\n";
    }
    else {
      echo "  <td><a href='interface/login/login_frame.php?site=$sfname'>Log In</a></td>\n";
    }
  }
  echo " </tr>\n";

  if ($config && $dbh !== FALSE) mysql_close($dbh);
}
?>
</table>
<form method='post' action='setup.php'>
<p><input type='submit' name='form_submit' value='Add New Site' /></p>
</form>
</center>
</body>
</html>
```

**Comment by maggienegm** [comment]
Whoops, I did not mean to close but had to fix my local repo and it resulted in closing this. Thanks for the thorough explanation @aethelwulffe . I'm working on a new solution.

**Comment by aethelwulffe** [comment]
I will check it out myself here soon.

**Pull request closed without merging**
