### PR TITLE
Appointment time checking code added

### PR DESCRIPTION
**Pull request by 2208Abhinav**
This will prevent appointment if time selected is absurd

### CODE REVIEW

**Comment by 2208Abhinav** [comment]
@teryhill @robbyoconnor please review this PR

**Comment by 2208Abhinav** [comment]
@teryhill I think we can make a table in database which will store the hours of service for clinics and use that data for condition inside **if**.

**Comment by naveen17797** [comment]
screenshot from 2018-03-28 22-41-41
we could follow this kind of approach , we can let user set working hours for each day (like shown below)
screenshot from 2018-03-28 22-44-01

**Comment by teryhill** [comment]
That sort of happens now. When you set up the system you should add "Provider" events in the calendar. These are Lunch, In time and out time. The system will pop up an alert stating no appoints for this provider if it is outside the in and our provider events. The issue I originally opened happens because the user is not heeding the alert warning.  Perhaps we should "Table" this until after GSoC .

But You guys are very creative with your ideas and suggestions, I like the fact that y'all are helping one another.

**Comment by 2208Abhinav** [comment]
@naveen17797 can you add your table part with my code.

**Comment by 2208Abhinav** [comment]
And tell me how can I help.

**Comment by teryhill** [comment]
Sorry my use of the word "Table" means not work on right now. Let's see if the project for calendar get's accepted and then we can push the Ideas to the one doing that project.

**Comment by 2208Abhinav** [comment]
@teryhill that sound good

**Pull request closed without merging**
