### PR TITLE
UI Fix: Load Lab Configuration Form Styling

### PR DESCRIPTION
**Pull request by jonathanzhang53**
**GCI: Task 11 in EHR UI Grab Bag**

## Description
Link: Procedures->Load compendium
Work: - Put fields in a form with a header

## Before
image

## After
image

### CODE REVIEW

**Comment by jonathanzhang53** [comment]
GCI: Task 11 in EHR UI Grab Bag

**Comment by muarachmann** [comment]
@jonathanzhang53 please remove the work in progress title

**Comment by muarachmann** [comment]
We will place it if it is deemed necessary

**Comment by robbyoconnor** [comment]
@muarachmann it's fine to put a WIP to this. This is helpful for the other students so nobody steps on people's toes.

**Comment by jonathanzhang53** [comment]
@muarachmann it's ready for review

**Comment by muarachmann** [comment]
Never mind its ok i guess it should be theme stuff

**Pull request merged**
