### PR TITLE
izi admin recreate from #1207

### PR DESCRIPTION
**Pull request by aethelwulffe**
Recreating mua's lost #1207 branch.  That repo was deleted, and had merge conflicts.

Ten file changes, with lots of stuff in odd places. @muarachmann please very very carefully review these changes and ensure we are not stomping on any commits made since these changes, as I was forced to directly copy each individual file.  Blame for commit time status should be looked at if there is any question for any of the changes.  Please verify the contents of each file.

### CODE REVIEW

**Comment by aethelwulffe** [comment]
Conflicting files
interface/usergroup/facilities.php
interface/usergroup/facility_user.php
The above should be checked especially carefully.
@muarachmann if you need to pull down this branch and use it to recreate your branch so you can edit, please do so, then dump #1207 and I will drop this one.

**Comment by muarachmann** [comment]
wow how did you do that

**Comment by muarachmann** [comment]
i think i will pull this and resolve the conflict then.

**Comment by aethelwulffe** [comment]
By copying each file.  I viewed the file, selected the "view raw" then copied and pasted the whole contents in...that is why you must very carefully review all changes to ensure they are not ones that I am essentially reverting from a commit that has been merged since you created #1207

**Comment by muarachmann** [comment]
Okay i will pull this then recommit.

**Comment by aethelwulffe** [comment]
Does it stomp on any recent changes?  That is what we are worried about.  Specifically state or review for that concern.

**Comment by aethelwulffe** [comment]
Re-tested yesterday and is OK.  Pulling the trigger.  Check yourself, but this is going in.

**Comment by muarachmann** [comment]
Yes it is ok on my end tested too some days back

**Pull request merged**
