### PR TITLE
Fixes #1352 - Language Select Field Too Small

### LINKED ISSUE #1352: Language Selector in Login Field Is Partially Hiding the Language Names
## Problem : 
As can be seen in the screenshot, the language select field is partially hiding the language names. A height of 28px is too small for it

### Screenshots : 
screenshot from 2018-12-08 16-50-55

## Possible Fix : 

#1353

### PR DESCRIPTION
**Pull request by bauripalash**
Fixes #1352 
Changed Height of the select field to 34px from 28px

Before : 
screenshot from 2018-12-08 16-50-55

After : 
screenshot from 2018-12-08 16-58-22

### CODE REVIEW

**Comment by muarachmann** [comment]
@bauripalash I dont have that effect see mine

screen shot 2018-12-08 at 1 36 10 pm

**Comment by bauripalash** [comment]
@muarachmann  I found that issue on https://ehr.librehealth.io/interface/login/login.php?site=default

**Comment by muarachmann** [comment]
I see that is not the latest codes wait let me get to robby.

**Comment by muarachmann** [comment]
@bauripalash please get the latest codes, if you still have that screen then i guess its our fault. I cant replicate that

**Comment by bauripalash** [comment]
Already Explained What Was Happening in Rocket Chat.

**Pull request closed without merging**
