### PR TITLE
Fix for usernames with spaces and underscores in Admin -> ACL

### PR DESCRIPTION
**Pull request by AfiMorgan**
@teryhill @naveen17797 

This should take care of the issue from #1093

### CODE REVIEW

**Comment by teryhill** [comment]
Thanks @AfiMorgan I really appreciate the help. I will get this tested.

Are you a student? If so I am sorry GSoC has closed for projects. But it would be great to have you making contributions. I appreciate all the help.

**Comment by AfiMorgan** [comment]
@teryhill Not a problem.
I am sure I will be contributing a lot more in the coming months.   I have been working with Andy Hickey testing out LibreEHR for an upcoming project.  
There were a couple of other issues that I have fixed on our dev environment while we were going through the software.  We were testing on a version from early Feb 2018.  I will make sure to compare it to the master branch and commit the changes when the gitlab repo is available again. 


Re: gitlab - Yes I have an account.  It's Afi_Morgan.

**Comment by teryhill** [comment]
@afimorgan the development tip is "experimental" until we clean it up for the release. 8^)
Looking forward to your contributions.

**Comment by teryhill** [comment]
@AfiMorgan this is the pr on gitlab  https://gitlab.com/librehealth/lh-ehr/merge_requests/1095

**Comment by teryhill** [comment]
Merged in GitLab, Thanks John for the fix. @AfiMorgan

**Pull request closed without merging**
