### PR TITLE
fix authenticated user unrestricted file upload #1401

### PR DESCRIPTION
**Pull request by robbyoconnor**
create methods for image verifcation in other to avoid code duplication
 renamed variables for better code readabilty

@prondubuisi -- just resolve the conflict from here -- sorry for trying to help. This is the state of the PR when before touched it

### CODE REVIEW

**Comment by robbyoconnor** [comment]
@prondubuisi 
```
git checkout master
git remote add robby https://github.com/robbyoconnor/lh-ehr.git
git fetch robby
git reset --hard robby/1404
git pull --rebase upstream master
... Fix conflict
git rebase --continue
git push -f origin master
```

**Comment by prondubuisi** [comment]
Thanks will do that ASAP

**Comment by aethelwulffe** [comment]
Standing by. Might be going home in another half-hour though.  Whooped.

**Comment by aethelwulffe** [comment]
Thanks for the input in any case Robby.  We just need to get this one
(and another 15 or so) off the list within the next week.  Too stale. 
Bad for business.

**Comment by muarachmann** [comment]
Nice work over here

**Comment by robbyoconnor** [comment]
These aren't simple conflicts to resolve

**Comment by prondubuisi** [comment]
Yes the sites changes from @muarachmann conflicted with this I think. @robbyoconnor I will have to rework this fix. Thanks.

**Comment by robbyoconnor** [comment]
@prondubuisi -- You can still use a lot -- there are two areas where you have a conflict -- but this isn't as easy as taking one or the other, but rather bits and pieces of each.

**Comment by aethelwulffe** [comment]
It is really a job for the original dev, because you basically have to look at your original changes and migrate them into the current changes.  I am not merging anything else related until this is in, and it will affect others after.  Some of these merge issues we have is due to concurrent solutions to the same issue, which puts off the next PR that pops up.  Picking and choosing after that becomes difficult and possibly political.  Political only in the sense that we are letting down volunteer devs due to mismanagement of the project.  Doing what we can at the moment though.  The end use case of this software warrants some difficulties.

**Comment by robbyoconnor** [comment]
@aethelwulffe -- I just put this up there so that they can have a reference to work from.

**Comment by aethelwulffe** [comment]
OK, now I am confused.  This isn't the original PR.  OK.  
Really fixing this isn't that big of a deal.  You just get a new branch, migrate the lines changed to the new branch with a side-by-side view diff, and push it.  I have to do it all the time.  Yes, it is a pisser to make a dev do that.  Sorry.

**Comment by robbyoconnor** [comment]
Basically what I did was reset to the last known state before I tried to
fix the conflict.

**Pull request closed without merging**
