### PR TITLE
A suitable UI for the libreehr setup procedure using multistep files.…

### PR DESCRIPTION
**Pull request by muarachmann**
… (/setup_ehr).Screenshots can be found in '/setup_ehr/screenshot' directory for issue#91

### CODE REVIEW

**Comment by aethelwulffe** [comment]
@muarachmann Hi!
Art here.
Could you tell us more about what you have here?

**Comment by muarachmann** [comment]
Hey, @aethelwulffe I created a new look and feel for the setup of libreehr at first installations screenshots of how it looks like can be found in the setup_ehr/screenshot folder. I wanted you all to see first and comment before making considerate changes and am a newbie too. I couldnt just tweak the base code like that . Any help or directives would be appreciated am willing to learn

**Comment by aethelwulffe** [comment]
@muarachmann 
This is a huge goofy code-base, and you did NOT decide to take on an easy task!  😄  Ia discussed your pull request last Wednesday on a phone call with someone, but neither of us have had the time to dive into your new package yet.  Bear with us!

**Comment by muarachmann** [comment]
@aethelwulffe, I have read the docs for developers and now can find myself around. Now ready to tweak the code. I am much more of front end but working on the back end too with a guy. What we would love to do is design and implement a new setup interface with a multi-step installation. Also we would love to roll back changes made to the database. So basically the setup would have next and prev buttons till the login screen.

**Comment by muarachmann** [comment]
screenshot from 2018-01-14 03-29-08

Setup page 1.
Though still styling.

**Comment by aethelwulffe** [comment]
This looks like an excellent start man!
Who is your Backend collaborator?
-Art

**Comment by codehimanshu** [comment]
Hi,
I would like to work on Backend in the setup module.

**Comment by muarachmann** [comment]
Hey @aethelwulffe  here is my backend partner @codehimanshu

**Comment by aethelwulffe** [comment]
Hi guys! @muarachmann @codehimanshu 
My name is Art.  I think it is really great that you two are coming aboard as a team.  I am sure you understand how valuable clean and process oriented setup and configuration tools are.  This is an important project, and anyone here will agree with me.

My advice:
1.  Unless there is a reason to have this in a completely separate repo, I advise creating the application in the DOCUMENT_ROOT/modules directory.  This is where cohesive mostly self-contained modular code should exist.  It may contain its own libraries etc... within that same directory and sub-directories.

2.  Keep your footprint small.  If you are using 3rd party packages within your module that do not already exist in /assets, pare them down to only what you need (plus the attribution/license material).

3.  Look for long-term maintainability.  It would be nice if the tool could check for updates to itself (with option to use newer versions), version the code base, and operate off of a configuration file that can be used to provide maintenance vs. hard-coding critical aspects.

4.  Keep in mind that we eventually want the setup tool to be able to ask configuration questions concerning inclusion of modules or special applications.

5.  While the above handles BASIC installations nicely, it would be really nice if an advanced/in-depth configuration script (once again easily maintained/updated) could also act as a config Wizard.  The idea here is that the installer could answer questions like "What is your clinic name?  What Theme would you like as default?  Add users?  Configure roles?  -currently, after installing, the typical user has to hunt such things down, discover them accidentally etc... after the application is installed.  I would gladly assist with providing lists of data points involved in basic setup for use.

6.  This same module would be great to provide upgrade processes and version/reversion/diff utilities.

**Comment by aethelwulffe** [comment]
NOTE:  There has been a lot of work done in this area related to database/backend items.  When you get to that point, I can help you find the resources related to that.  Much of that (not all) is contained in this repo PR's and Issues.  I also have the windows executable compiler config file for the innosetup tool.

**Comment by muarachmann** [comment]
ok

**Comment by muarachmann** [comment]
hey @aethelwulffe have done some block of code on versioning of the system.I hardcoded the optimal version in compliance with the INSTALL.MD file and check if your php_version is lower than that if yes i ask your permission to update to the hardcoded version. (7.0.27) for my case here. i run the command using `shell_exec`same for the mysql version.I wish to know if this appraoch is feasible.

**Comment by aethelwulffe** [comment]
What do you mean "update to the hardcoded version"?  I think you are saying "find out what version they are running, then offer to update the PHP version, and do the same with mysql".  Right?  Note that MariaDB might be the actual version of mySQL.

If my interpretation is correct, then yes, this is a reasonable approach.  There must be some option to install other than one that requires a dependency update though.  The other issue is where the version is one that is not fully supported, or has some issue with it (such as 7.1).

What is your test server system?  
Remember that shell_exec and things that use phpCLI have different requirements between Windows and various Linux systems.  We need detection, then logic, including path pipes.

**Comment by muarachmann** [comment]
I use apache server in the linux system.And yes i have banned versions above 7.1. By hardcoded i mean i wrote a variable `$latestVersion = "7.0.27"` for example then i checked if the cuurent version installed on your machine is less than this.

**Comment by muarachmann** [comment]
Also i would love to know if we are to install (upgrade the sys in the background) for example use of a button click and shows a loader or display a page with all commands that the user has to type manually is that possible (i mean to run php via command liine )

**Comment by aethelwulffe** [comment]
Simple...We are to do whatever you think is a good flexible, maintainable, capable, and useful application goal.
   You are designing it!  Do what you think needs to be done.  If system upgrades are within the scope of your tool, then _just do it well_.  You get to decide these things...it's your parade!

**Comment by muarachmann** [comment]
Heu @aethelwulffe are you there
am good to go that is begin wrting to the database but am kind of loast could you help me

**Comment by aethelwulffe** [comment]
@muarachmann Sure buddy.  I have been out for a few days.  Tell me where you are having issues and I will try to help.

**Comment by muarachmann** [comment]
did some revamping on the setup procedure. now found in /modules/setup according to @aethelwulffe

Also verified php version and mysql version of user and checks if it meets required conditions
If good but not optimal, demands upgrade of suitable versions
If bad doesnt allow user to continue to the setup until he follows instructions found in the install.md file
Looking forward to add stuffs like roll back changes that is after database has been created if user wishes to cancel the by clicking back or cancel it undoes changes made in the databse by setup
Also looking forward in creating a creen for custom settings like : theme-color , language , hospital name , etc

**Comment by muarachmann** [comment]
I will need help on how i can make rool back changes to the database

**Comment by muarachmann** [comment]
@aethelwulffe , @teryhill  i am closing this PR this will handle the setup improvements here is the new PR 
https://github.com/LibreHealthIO/lh-ehr/pull/1135

**Comment by muarachmann** [comment]
@aethelwulffe , @tmccormi closing this too cause it was the initial idea of the setup module and has no use again. Just makes the PR count many for nothing

**Pull request closed without merging**
