### PR TITLE
repair relative link

### PR DESCRIPTION
**Pull request by aethelwulffe**
issue #1249

### CODE REVIEW

**Comment by tmccormi** [comment]
Nope...  now the path is closer but still not correct
userdata_css

http://localhost/lh-ehr-dev/interface/main/css/userdata.css

**Comment by aethelwulffe** [comment]
Yeah, I see.
Checking to see why the hell not.

**Comment by aethelwulffe** [comment]
K...should work.  Can't test right now.

**Comment by tmccormi** [comment]
not quite, however if you drop the leading slash it clears that particular error.    The calendar is still borked, but we are down to 1 error now...
index-token

**Comment by tmccormi** [comment]
I've fixed the css path.  Looking at the index.php issue

**Pull request merged**
