### PR TITLE
Fix : Themes not consistently implemented #1286

### LINKED ISSUE #1286: Themes not consistently implemented
The themes in rel_101 were consistent colors across (nearly) all parts of the UI, now it appears they only apply to some things (like demographic summary)

REL_101:
tan-theme-rel101

DEVTIP:
tan-theme-devtip

### PR DESCRIPTION
**Pull request by muarachmann**
@tmccormi fixed #1286 for flowbard menu take a look so i can go through all the menu

### CODE REVIEW

**Comment by muarachmann** [comment]
Done till the patient/Clients menu. But soap menu showing weird still looking for the appropriate file for it. Can't seem to figure out.... the css keeps overriding it when i apply the theme. Once i figure it i will make a PR for it. For now i head over to fees ....

**Comment by muarachmann** [comment]
@tmccormi  I left the blank form thinking this might be ok for the background to be white since it is going to be printed. just my thought should i change it to suite the theme's color?

**Comment by muarachmann** [comment]
@teryhill , @aethelwulffe , @tmccormi I just fixed the calendar theme also. I like it with the brown color for the calendar.... IMO 😄 . Take a look at how it displays on prism and purple themes. But .... i could be changed waiting for your feedback if it is okay by you

screen shot 2018-11-24 at 9 47 15 am

screen shot 2018-11-24 at 9 45 52 am

**Comment by muarachmann** [comment]
I think i wrapped up with the last menus. I am done with this @tmccormi

**Comment by muarachmann** [comment]
@aethelwulffe  i think this was a rapid fix demmanded by @tmccormi in.  I went from menu to menu to check them. Starting with calendar

**Comment by muarachmann** [comment]
So you will have to check each menu. But i think this can hold since i might be working on a better solution for a default theme and customisable theme

**Comment by muarachmann** [comment]
@aethelwulffe , @tmccormi this is ok for a review now.

**Comment by aethelwulffe** [comment]
Calendar changes coming soon....but pulling this in.

**Comment by muarachmann** [comment]
Actually i loved the way calendar's screen was displayed - https://github.com/LibreHealthIO/lh-ehr/pull/1287#issuecomment-441353046 :) was reluctant to change it all.But the theme fits into it just fine. When i get time i would fix the one theme issue stuff

**Comment by aethelwulffe** [comment]
All righty then.  I need to ask grandpa about some code he has related to the calendar, but let's get this moved in.  I just did the setup script change review, then merge, so I need to check some "lots of commits merged" testing before doing any more this morning.  Best way to break stuff is to test PR branches, then later not look at the merged master for overall effect.

**Comment by muarachmann** [comment]
Sure.

**Comment by aethelwulffe** [comment]
Also merged the report gen module.  It is clean code, and can't really break anything else.

**Pull request merged**
