### PR TITLE
Popup success on adding new issue and closes modal appropriately

### PR DESCRIPTION
**Pull request by muarachmann**

### CODE REVIEW

**Comment by muarachmann** [comment]
@Trodrige , @teryhill try adding a new issue from the encounters table.This clodes the modal. The popup i put was just to confirm that the issue has been added

**Comment by teryhill** [comment]
@muarachmann  Got this in testing.

image

**Comment by teryhill** [comment]
If I remove the fancybox close and replace it with the original window close it works fine.

**Comment by muarachmann** [comment]
@terry where did you go

**Comment by muarachmann** [comment]
I followed select patient -> add new encounter -> add new issue

**Comment by teryhill** [comment]
Thru issues on the demographics screen. I get your alert but on in this section of code that calls the program you made the change to fancybox is not loaded.

image

**Comment by teryhill** [comment]
This is the screen you are seeing 

image

**Comment by teryhill** [comment]
Or this is the screen you are seeing

image

**Comment by teryhill** [comment]
@muarachmann  what I am saying is that the program you fixed add_edit_issue.php is called from other programs besides the popup, some of which load fancybox and some don't. In this case add_edit_issue.php is called by these 3 programs 

interface\forms\patient_encounter\common.php
interface\patient_file\problem_encounter.php
interface\patient_file\summary\stats_full.php

So you can make a change that seams simple enough but when you test and work with the software another issue pops up some where else.

**Comment by muarachmann** [comment]
Okay

**Comment by teryhill** [comment]
Tested and it works well

**Comment by teryhill** [comment]
closed in gitlab so closing here

**Pull request closed without merging**
