### PR TITLE
Exclude individual items from claims

### PR DESCRIPTION
**Pull request by teryhill**
Exclude individual items from claims. #266

### CODE REVIEW

**Comment by tmccormi** [comment]
There are still conflicts
Conflicting files
library/globals.inc.php
sql/0_0_1-to-1_0_0_upgrade.sql
sql/database.sql

**Comment by teryhill** [comment]
I changed them again

**Comment by tmccormi** [comment]
nope.  The same files are still in conflict.

**Comment by tmccormi** [comment]
I can fix it from the command line if you like

**Comment by teryhill** [comment]
Go for it I am getting failed to sync errors

**Comment by tmccormi** [comment]
Done.

**Pull request merged**
