### PR TITLE
Added some setting recommendations.

### PR DESCRIPTION
**Pull request by alpinus4**
I changed bad recommended value of key_buffer_size to value from INSTALL.md (changed from 10M to 1024M).
Fixes https://github.com/LibreHealthIO/LibreEHR/issues/912

### CODE REVIEW

**Comment by aethelwulffe** [comment]
What about table_open_cache?
These go hand in hand.
-I also swear that we addressed these previously.  I know that I built the XAMPP distro with a similar buffer setting.

**Comment by alpinus4** [comment]
@aethelwulffe I haven't found _table_open_cache_ parameter in both INSTALL.md and setup.php and I don't know anything about it :/ Could you tell me more about it?

**Comment by aethelwulffe** [comment]
That is because we are not giving recommendations and we probably (I 
think) should if we recommend settings for other related parameters.

Searching for "table_open_cache" in the INNODB context should give you a 
ton of resources.

**Comment by alpinus4** [comment]
Thanks @aethelwulffe .
So, should I remove this PR, or learn more about setting up the Mysql server and add recommendations?

**Comment by aethelwulffe** [comment]
No, don't close this PR.  Pretty sure it should go forward.
If you care to look at other elements before we merge, that is fine, but I suppose we need to get this approved.

**Comment by alpinus4** [comment]
@aethelwulffe I added table_open_cache recommendation as 256 and I decreased key_buffer_size to 256M.
I have no idea for change anything other and think that it isn't necessary, but if you have any suggestions....

**Comment by aethelwulffe** [comment]
@alpinus4 No suggestions here.  These seem perfectly reasonable settings to me.
The main issue here is that we are (supposedly) INNODB, which doesn't give a hoot about these settings at all.

**Comment by alpinus4** [comment]
@aethelwulffe How about now?

**Comment by aethelwulffe** [comment]
@alpinus4 I think the new setting recommendations are totally reasonable.  I wish we could do some actual performance testing with various settings.

**Comment by Trodrige** [comment]
Hi, @alpinus4 . We've moved to GitLab. PR owners are moving their work to GitLab. Can you do this buddy?

Thanks,
Rodrige.

**Comment by teryhill** [comment]
Merged in Gitlab

**Pull request closed without merging**
